### ISSUE TITLE
wasm code accessing data on the native stack

### ISSUE THREAD

**Issue by MarkSwanson** [sunfishcode/wasmstandalone#8]
It doesn't seem useful to give wasm code references to data structures on the native stack because:
* the wasm code can only push/pop values on to the native stack - it can't directly reference data on the stack (because the stack is outside the 4/8 GiB wasm linear memory region).

Is this correct, or is there some mechanism I'm overlooking? 

Thanks!

**Comment by sunfishcode** [comment]
Wasm code itself cannot explicitly access the native stack. You're correct that the native stack is outside of any linear memory, and outside of the linear memory guard region.

Compiled wasm code uses the native stack to hold wasm operand stack values and wasm local variables that don't fit in registers, and also call bookkeeping -- arguments, return values, saved registers, and return addresses. These are all under control of the compiler.

Does that answer your question?

**Comment by MarkSwanson** [comment]
Perfectly. Thank you!
